### ISSUE TITLE
giveaway.su

### ISSUE THREAD

**Issue by ghost** [gekkedev/GiveawayKiller#3]
Hi.
Seems this new script don't works with this site, every time i try to enter a GA the site ask to install a extension, with the old script (the enhancer) never had this kind of problems, is fixable?

**Comment by gekkedev** [comment]
Indeed, it must have been broken for a long time. Fixed it by change https://github.com/gekkedev/GiveawayKiller/commit/b692c5adb0f6020ae12a430ea784de869d37b236.
Automatic Steam group joining could technically be working, but only if the url contains `?killerjoin` or `&killerjoin` in the end. Adding this on giveaway.su might be difficult, but it can be added to other sites once applicable.
I've disabled the feature very quickly again in https://github.com/gekkedev/GiveawayKiller/commit/1bbfa3bfe58e3e032477d6b22c0ebec46189e8f4...

**Comment by ghost** [comment]
thanks for the reply and fixes, have a nice day :)
