### ISSUE TITLE
hey, can you add https://gamecode.win ?

### ISSUE THREAD

**Issue by yuningning520** [gekkedev/GiveawayKiller#4]
hey, can you add https://gamecode.win ?

**Comment by gekkedev** [comment]
Sure, but it seems like not much more than ad removal can be done here. They seem to enforce account linking which is something that shouldn't be automated fully, except for the usual steam login.

**Comment by yuningning520** [comment]
Can you add to Automatic login function
https://greasyfork.org/scripts/32128-  auto complete this can do

**Comment by vaibhavhrt** [comment]
Many of the tasks on gamecode are just link visits and then click verify. That can be automated.

**Comment by gekkedev** [comment]
Sorry for the delay, I implemented the removal of Google ads and the annoying Kinguin popups.
